### ISSUE TITLE
Support for mathematical symbols

### ISSUE THREAD

**Issue by Vivek-kumr** [DahlitzFlorian/math-tokenizer#1]
Does not support mathematical expressions with equals to symbol("=")

Shows following error for input text as : "2x^3  +  (3X -1) = 9"
if intermediate_result1[0] == intermediate_result2[0]:
IndexError: list index out of range

**Comment by DahlitzFlorian** [comment]
Nevermind that someone would discover it and use it. In fact, I wrote this more than three years ago, when I had nearly zero knowledge of these things. Today, I would implement it differently, but there is no need for it as I'm sure there are better packages out there solving the same problem.

But thanks for the report. I'm aware that this is not supported at the moment and I don't see myself to extend this little package.
